name: guptik_desktop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  lucide_icons: ^0.257.0
  glassmorphism: ^3.0.0
  qr_flutter: ^4.1.0
  window_manager: ^0.5.1
  device_info_plus: ^12.3.0
  file_picker: ^10.3.10
  flutter_markdown: ^0.7.0
  process_run: ^0.13.0
  path_provider: ^2.1.5
  postgres: ^3.4.0
  sqflite_common_ffi: ^2.3.2
  supabase_flutter: ^2.3.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.5.4
  uuid: ^4.0.0
  video_player: ^2.11.1
  http: ^1.2.0
  webview_windows: ^0.4.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0
  video_player_win: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logonobg.png